const $=s=>document.querySelector(s);let DATA=null,token='',state={group:'G1',worker:'1',name:'',stage:'nc',index:0,answers:{nc:{},pcpn:{},ti:{},r1:{}}};
const stages={nc:{name:'PHASE 1 · N / C',title:'Review complete persona histories',help:'Each group has two complete histories. Scroll through every session before giving Naturalness and Coherence ratings from 1 to 3.'},pcpn:{name:'PHASE 2 · PC / PN',title:'Infer hidden preferences',help:'The preference annotation is hidden. Write your own preference guess (PC), then judge whether the preference emerges naturally (PN).'},ti:{name:'PHASE 3 · TI',title:'Identify the target item',help:'The query and activated preference values are visible. Choose the one correct target from ten visually similar candidates.'},r1:{name:'PHASE 4 · R@1',title:'Find the target from history',help:'Use the original query and the complete interaction history. Each persona has six target products across Fashion, Food, and Movie.'}};
fetch('audit_data.json?v=20260923-paths', {cache:'no-store'}).then(r=>r.json()).then(d=>{DATA=d;ready()}).catch(()=>$('#saveStatus').textContent='Data failed to load');function ready(){['consent','name','token'].forEach(id=>$('#'+id).addEventListener('input',()=>$('#start').disabled=!(DATA&&$('#consent').checked&&$('#name').value.trim()&&$('#token').value.trim())))}
$('#start').onclick=()=>{state.group=$('#group').value;state.worker=$('#worker').value;state.name=$('#name').value.trim();token=$('#token').value.trim();state.stage='nc';state.index=0;$('#intro').classList.add('hidden');$('#study').classList.remove('hidden');render()};
function group(){return DATA.groups.find(g=>g.group_id===state.group)}function list(){return state.stage==='nc'||state.stage==='r1'?group().personas:group()[state.stage==='pcpn'?'pc_pn':'ti']}function cur(){return list()[state.index]}
function render(){const s=stages[state.stage],n=list().length;$('#stageName').textContent=s.name;$('#stageTitle').textContent=s.title;$('#stageHelp').textContent=s.help;$('#counter').textContent=`${state.index+1} / ${n}`;$('#bar').style.width=(100*(state.index+1)/n)+'%';$('#card').innerHTML=state.stage==='nc'?historyCard(cur(),true):state.stage==='pcpn'?pcpnCard(cur()):state.stage==='ti'?tiCard(cur()):r1Card(cur());$('#next').textContent=state.stage==='r1'&&state.index===n-1?'Finish & download →':'Save & continue →';$('#back').textContent=state.index===0&&state.stage==='nc'?'← Intro':'← Back';wire();window.scrollTo({top:0,behavior:'smooth'})}
function historyMarkup(p){return `<div class="persona"><div><h3>${esc(p.persona.name||'Persona')}</h3><span class="tag">persona ${esc(p.persona_id)}</span></div><p>${esc(p.persona.short_persona||'Long-term assistant user')}</p></div><div class="history">${p.sessions.map((s,i)=>`<section class="session"><div class="session-label">SESSION ${i+1} · ${esc(s.entry_id)}</div><div class="chat">${s.messages.map(m=>`<div class="bubble ${m.role==='user'?'user':'assistant'}"><div class="role">${m.role.toUpperCase()}</div>${m.content.map(c=>c.type==='text'?esc(c.text):(c.local_image?`<img class="inline-image" loading="lazy" src="${esc(c.local_image)}" alt="Conversation image">`:`<div class="image-wrap" data-path="${esc(c.path)}"><div class="placeholder">Loading conversation image…</div></div>`)).join('')}</div>`).join('')}</div></section>`).join('')}</div>`}
function historyCard(p,score){const a=state.answers.nc[p.persona_id]||{};return `<article class="task"><div class="task-head"><span class="tag">${esc(p.persona_id)}</span><span class="tag">${p.sessions.length} complete sessions</span><b>Persona history ${state.index+1} of 2</b></div>${historyMarkup(p)}${score?`<div class="eval"><h3>Rate this complete history</h3><div class="eval-grid">${scale('n','N · Naturalness','How much does it resemble everyday communication?',a.n)}${scale('c','C · Coherence','How logically and contextually consistent is the history?',a.c)}</div></div>`:''}</article>`}
function pcpnCard(x){const a=state.answers.pcpn[x.task_id]||{};return `<article class="task"><div class="task-head"><span class="tag">${esc(x.domain)}</span><span class="tag">hidden preference</span><b>Session ${state.index+1} of 10</b></div>${sessionMarkup(x.session)}<div class="eval"><div class="criterion"><strong>PC · Preference Correctness</strong><p>What preference does this session express? Use your own words. Do not search for a target label.</p><textarea id="guess" class="free" placeholder="The user appears to prefer …">${esc(a.guess||'')}</textarea></div>${binary('pn','PN · Preference Naturalness','Does the preference emerge naturally instead of being artificially inserted?',a.pn)}</div></article>`}
function sessionMarkup(s){return `<div class="session one"><div class="session-label">${esc(s.entry_id)}</div><div class="chat">${s.messages.map(m=>`<div class="bubble ${m.role==='user'?'user':'assistant'}"><div class="role">${m.role.toUpperCase()}</div>${m.content.map(c=>c.type==='text'?esc(c.text):(c.local_image?`<img class="inline-image" loading="lazy" src="${esc(c.local_image)}" alt="Conversation image">`:`<div class="image-wrap" data-path="${esc(c.path)}"><div class="placeholder">Loading conversation image…</div></div>`)).join('')}</div>`).join('')}</div></div>`}
function tiCard(x){const a=state.answers.ti[x.task_id]||{};return `<article class="task"><div class="task-head"><span class="tag">${esc(x.domain)}</span><b>TI target ${state.index+1} of 5</b></div><div class="query"><b>Original query</b><br>${esc(x.query)}</div><div class="preferences"><b>Activated preferences</b><br>${Object.entries(x.activated_preferences||{}).map(([k,v])=>`${esc(k)}: ${esc(Array.isArray(v)?v.join(', '):v)}`).join(' · ')}</div><div class="product-set"><h4>Choose the correct target</h4><small>Exactly one candidate is correct.</small><div class="candidates">${x.candidates.map(c=>candidate(c,a.choice)).join('')}</div></div></article>`}
function r1Card(p){const items=group().r1.filter(x=>x.persona_id===p.persona_id);return `<article class="task"><div class="task-head"><span class="tag">persona ${esc(p.persona_id)}</span><span class="tag">complete history · ${p.sessions.length} sessions</span><b>Persona ${state.index+1} of 2</b></div>${historyMarkup(p)}<div class="product-set"><h3>Six target-product tasks</h3><p>For each query, use the complete history above and choose the best candidate.</p>${items.map(x=>`<div class="r1-item"><div class="query"><b>${esc(x.domain)} · ${esc(x.query)}</b></div><div class="candidates">${x.candidates.map(c=>candidate(c,(state.answers.r1[x.task_id]||{}).choice,x.task_id)).join('')}</div></div>`).join('')}</div></article>`}
function candidate(c,selected,key=''){const movie=c.domain==='movie';const a=c.attributes||{};const meta=movie?`<div class="movie-meta"><span>${esc(a.release_era||'')}</span><span>${esc(a.original_language||'')}</span><span>${esc(Array.isArray(a.production_region)?a.production_region.join(', '):(a.production_region||''))}</span>${a.director?`<span>Director: ${esc(Array.isArray(a.director)?a.director.join(', '):a.director)}</span>`:''}${a.lead_cast?`<span>Cast: ${esc(Array.isArray(a.lead_cast)?a.lead_cast.slice(0,3).join(', '):a.lead_cast)}</span>`:''}</div>`:'';return `<button class="candidate ${selected===c.id?'selected':''}" data-candidate="${esc(c.id)}" data-task="${esc(key)}">${movie?'':(c.local_image?`<img loading="lazy" src="${esc(c.local_image)}" alt="">`:`<div class="missing-image">Image unavailable</div>`)}<span class="ctitle">${esc(c.title)}</span>${meta}</button>`}
function scale(key,label,desc,val){return `<div class="criterion"><strong>${label}</strong><p>${desc}</p><div class="scale">${[1,2,3].map(v=>`<button data-key="${key}" data-value="${v}" class="${val===v?'selected':''}">${v}</button>`).join('')}</div></div>`}function binary(key,label,desc,val){return `<div class="criterion"><strong>${label}</strong><p>${desc}</p><div class="choice"><button data-key="${key}" data-value="1" class="${val===1?'selected':''}">1 · yes</button><button data-key="${key}" data-value="0" class="${val===0?'selected':''}">0 · no</button></div></div>`}
function wire(){document.querySelectorAll('.scale button,.choice button').forEach(b=>b.onclick=()=>{const k=state.stage==='nc'?cur().persona_id:cur().task_id,a=state.answers[state.stage][k]||{};a[b.dataset.key]=+b.dataset.value;state.answers[state.stage][k]=a;b.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b))});document.querySelectorAll('.candidate').forEach(b=>b.onclick=()=>{const key=state.stage==='ti'?cur().task_id:b.dataset.task;const a=state.answers[state.stage][key]||{};a.choice=b.dataset.candidate;state.answers[state.stage][key]=a;b.parentElement.querySelectorAll('.candidate').forEach(x=>x.classList.toggle('selected',x===b))});const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){loadConvImage(e.target,e.target.dataset.path);io.unobserve(e.target)}}),{rootMargin:'500px'});document.querySelectorAll('.image-wrap').forEach(x=>io.observe(x))}
const imageQueue=[];let imageActive=0;
function loadConvImage(el,path){imageQueue.push({el,path});pumpImages()}
function pumpImages(){while(imageActive<4&&imageQueue.length){const job=imageQueue.shift();if(!job.el.isConnected)continue;imageActive++;fetchConvImage(job.el,job.path).finally(()=>{imageActive--;pumpImages()})}}
async function fetchConvImage(el,path){const u='https://huggingface.co/datasets/ronpay/PersonaRec/resolve/main/'+path;let error;for(let attempt=0;attempt<3;attempt++){try{const r=await fetch(u,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(60000)});if(!r.ok)throw new Error('HTTP '+r.status);const b=await r.blob();const img=document.createElement('img');const url=URL.createObjectURL(b);img.src=url;try{await img.decode()}catch(e){URL.revokeObjectURL(url);throw e}img.onload=()=>URL.revokeObjectURL(url);el.replaceChildren(img);return}catch(e){error=e;if(/HTTP (401|403|404)/.test(e.message))break;if(attempt<2)await new Promise(r=>setTimeout(r,1000*(attempt+1)))}}const msg=document.createElement('div');msg.className='placeholder';msg.textContent='Image could not load ('+error.message+'). '+(/401|403/.test(error.message)?'Check your Hugging Face token and dataset access. ':'');const retry=document.createElement('button');retry.textContent='Retry image';retry.onclick=()=>{msg.textContent='Loading conversation image…';loadConvImage(el,path)};el.replaceChildren(msg,retry)}

function valid(){if(state.stage==='r1'){return group().r1.filter(x=>x.persona_id===cur().persona_id).every(x=>state.answers.r1[x.task_id]?.choice)}const k=state.stage==='nc'?cur().persona_id:cur().task_id,a=state.answers[state.stage][k]||{};if(state.stage==='nc'&&!(a.n&&a.c))return false;if(state.stage==='pcpn'){a.guess=$('#guess').value.trim();state.answers.pcpn[k]=a;if(!a.guess||typeof a.pn!=='number')return false}if(state.stage==='ti'&&!a.choice)return false;return true}
$('#next').onclick=()=>{if(!valid()){alert('Please complete every response on this page before continuing.');return}const n=list().length;if(state.index<n-1){state.index++;render()}else if(state.stage==='nc'){state.stage='pcpn';state.index=0;render()}else if(state.stage==='pcpn'){state.stage='ti';state.index=0;render()}else if(state.stage==='ti'){state.stage='r1';state.index=0;render()}else finish()};
$('#back').onclick=()=>{if(state.index>0){state.index--;render()}else if(state.stage==='pcpn'){state.stage='nc';state.index=1;render()}else if(state.stage==='ti'){state.stage='pcpn';state.index=9;render()}else if(state.stage==='r1'){state.stage='ti';state.index=4;render()}else{$('#study').classList.add('hidden');$('#intro').classList.remove('hidden')}};
function finish(){state.answers.meta={group_id:state.group,volunteer_number:state.worker,annotator_name:state.name,completed_at:new Date().toISOString(),schema_version:'v1'};$('#study').classList.add('hidden');$('#done').classList.remove('hidden')};$('#download').onclick=()=>{const a=document.createElement('a'),b=new Blob([JSON.stringify(state.answers,null,2)],{type:'application/json'});a.href=URL.createObjectURL(b);a.download=`personarec-${safe(state.name)}-${state.group}-v${state.worker}.json`;a.click();URL.revokeObjectURL(a.href)};function safe(x){return x.toLowerCase().replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'')||'volunteer'}function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
