const $=s=>document.querySelector(s);
let DATA=null,imageToken='',state={volunteer:'V1',name:'',phase:0,index:0,answers:{interaction:{},imagination:{}}};
const phases=[{key:'interaction',name:'PHASE 1 · COMPLETE PERSONA HISTORIES',title:'Read one complete persona history',help:'Scroll from the first session to the last. Then rate the entire history for consistency and realism.'},{key:'imagination',name:'PHASE 2 · PREFERENCE REVELATION',title:'Infer what the session reveals',help:'The target preference is hidden. Read each session, write your best guess, and judge whether the revelation feels natural.'}];
fetch('volunteer_tasks.json').then(r=>r.json()).then(d=>{DATA=d;updateStart()}).catch(()=>$('#saveStatus').textContent='Could not load task set');
['consent','annotatorName','hfToken'].forEach(id=>$('#'+id).addEventListener('input',updateStart));
function updateStart(){const ok=DATA&&$('#consent').checked&&$('#annotatorName').value.trim()&&$('#hfToken').value.trim();$('#start').disabled=!ok}
$('#start').onclick=()=>{state={volunteer:$('#volunteer').value,name:$('#annotatorName').value.trim(),phase:0,index:0,answers:{interaction:{},imagination:{}}};imageToken=$('#hfToken').value.trim();$('#intro').classList.add('hidden');$('#study').classList.remove('hidden');render()};
function assignment(){return DATA.volunteers.find(v=>v.volunteer_id===state.volunteer)}function list(){return assignment()[phases[state.phase].key]}function current(){return list()[state.index]}function itemKey(){return state.phase===0?current().persona_case_id:current().session_id}
function render(){const p=phases[state.phase],n=list().length;$('#phaseEyebrow').textContent=p.name;$('#phaseTitle').textContent=p.title;$('#phaseHelp').textContent=p.help;$('#progressLabel').textContent=`${state.index+1} / ${n}`;$('#progressBar').style.width=((state.index+1)/n*100)+'%';$('#back').textContent=state.index===0&&state.phase===0?'← Intro':'← Back';$('#next').innerHTML=state.phase===1&&state.index===n-1?'Finish & download <span>✓</span>':'Save & continue <span>→</span>';$('#taskCard').innerHTML=state.phase===0?interactionCard(current()):imaginationCard(current());wire();window.scrollTo({top:0,behavior:'smooth'})}
function interactionCard(c){let h=`<article class="task-shell"><div class="task-meta"><span class="tag">${esc(c.persona_label)}</span><span class="tag">${c.sessions.length} sessions</span><span class="tag">${esc(c.persona_case_id)}</span><span class="task-title">Complete history ${state.index+1} of 2</span></div><div class="persona"><div><h4>${esc(c.persona.name)}</h4><span class="tag">Persona ${esc(String(c.persona.user_id))}</span></div><p>${esc(c.persona.short)}</p></div><div class="history-scroll">`;
c.sessions.forEach((s,i)=>{h+=`<section class="session"><div class="session-label">SESSION ${i+1} · ${esc(s.category||'conversation')} · ${esc(s.session_id)}</div><div class="chat">${s.messages.map(m=>`<div class="bubble ${m.role==='user'?'user':'assistant'}"><div class="role">${m.role==='user'?'USER':'ASSISTANT'}</div>${esc(m.text)}</div>`).join('')}</div>`;if(s.image_path)h+=`<div class="image-wrap" data-path="${esc(s.image_path)}" data-pilot="${esc(s.pilot_id)}"><div class="image-placeholder">Loading image…</div></div>`;h+='</section>'});
h+='</div><div class="eval"><h3>Rate this complete persona history</h3><div class="eval-grid">'+binary('consistency','Conversational Consistency','Does the full history remain logically and contextually consistent?')+binary('realism','Interaction Realism','Does the full history resemble everyday human–MLLM interaction?')+'</div></div></article>';return h}
function imaginationCard(s){let h=`<article class="task-shell"><div class="task-meta"><span class="tag">${esc(s.category||'session')}</span><span class="tag">${esc(s.expression||'conversation')}</span><span class="tag">${esc(s.session_id)}</span><span class="task-title">Preference session ${state.index+1} of 10</span></div><div class="chat">${s.messages.map(m=>`<div class="bubble ${m.role==='user'?'user':'assistant'}"><div class="role">${m.role==='user'?'USER':'ASSISTANT'}</div>${esc(m.text)}</div>`).join('')}</div>`;if(s.image_path)h+=`<div class="image-wrap" data-path="${esc(s.image_path)}" data-pilot="${esc(s.pilot_id)}"><div class="image-placeholder">Loading image…</div></div>`;h+=`<div class="eval"><div class="criterion"><strong>Imagination Fidelity · your guess</strong><p>What visual preference does this session convey? Describe it in your own words.</p><textarea class="free-text" id="guess" placeholder="For example: preference for …">${esc((state.answers.imagination[s.session_id]||{}).guess||'')}</textarea></div>${binary('naturalness','Revelation Naturalness','Does the preference emerge organically rather than being explicitly inserted?')}</div></article>`;return h}
function binary(key,label,desc){const a=state.answers[phases[state.phase].key][itemKey()]||{};return `<div class="criterion"><strong>${label}</strong><p>${desc}</p><div class="choice"><button data-key="${key}" data-value="1" class="${a[key]===1?'selected':''}">1 · yes</button><button data-key="${key}" data-value="0" class="${a[key]===0?'selected':''}">0 · no</button></div></div>`}
function wire(){document.querySelectorAll('.choice button').forEach(b=>b.onclick=()=>{const k=itemKey(),a=state.answers[phases[state.phase].key][k]||{};a[b.dataset.key]=+b.dataset.value;state.answers[phases[state.phase].key][k]=a;document.querySelectorAll(`[data-key="${b.dataset.key}"]`).forEach(x=>x.classList.toggle('selected',x===b))});const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const w=e.target;loadImage(w,w.dataset.path,w.dataset.pilot);observer.unobserve(w)}}),{rootMargin:'500px'});document.querySelectorAll('.image-wrap').forEach(w=>observer.observe(w))}
function loadImage(w,path,pilot){const url='https://huggingface.co/datasets/ronpay/PersonaIMG/resolve/main/'+(path.startsWith('images/')?'pilot/'+pilot+'/'+path:path)+'?download=true';fetch(url,{headers:{Authorization:'Bearer '+imageToken}}).then(r=>r.ok?r.blob():Promise.reject()).then(b=>{const img=document.createElement('img');img.alt='Session image';img.loading='lazy';img.src=URL.createObjectURL(b);w.replaceChildren(img)}).catch(()=>w.innerHTML='<div class="image-placeholder">Image unavailable; continue with the text session.</div>')}
$('#back').onclick=()=>{if(state.index>0){state.index--;render()}else if(state.phase>0){state.phase--;state.index=list().length-1;render()}else{$('#study').classList.add('hidden');$('#intro').classList.remove('hidden')}};
$('#next').onclick=()=>{if(!save())return;const n=list().length;if(state.index<n-1){state.index++;render()}else if(state.phase===0){state.phase=1;state.index=0;render()}else finish()};
function save(){const k=itemKey(),a=state.answers[phases[state.phase].key][k]||{};if(state.phase===0&&!(('consistency'in a)&&('realism'in a))){alert('Please answer both binary questions.');return false}if(state.phase===1){a.guess=$('#guess').value.trim();if(!a.guess||!('naturalness'in a)){alert('Please enter a guess and choose 0 or 1.');return false}}state.answers[phases[state.phase].key][k]=a;return true}
function finish(){state.answers.meta={volunteer_id:state.volunteer,annotator_name:state.name,completed_at:new Date().toISOString(),schema_version:'v2'};localStorage.setItem('personaimg-'+state.volunteer+'-'+state.name,JSON.stringify(state.answers));$('#study').classList.add('hidden');$('#done').classList.remove('hidden')}
$('#download').onclick=()=>{const blob=new Blob([JSON.stringify(state.answers,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`personaimg-${safe(state.name)}-${state.volunteer}-responses.json`;a.click();URL.revokeObjectURL(a.href)};$('#restart').onclick=()=>{$('#done').classList.add('hidden');$('#study').classList.remove('hidden');state.phase=0;state.index=0;render()};
function safe(v){return v.toLowerCase().replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'')||'annotator'}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
